---
title: "Day 9 Comp"
author: "Ryan Munnikhuis"
date: "8/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
library(lubridate)
library(kableExtra)
library(janitor)
library(reprex)
```
### janitor::get_dupes
```{r}
view(starwars)

sw_dupes = get_dupes(starwars)

sw_dupes_ec_hc = starwars %>% 
  get_dupes(eye_color, hair_color)

sw_dupes_ec_hc

```

### dplyr::across()

```{r}
sw_across = starwars %>% mutate(dplyr::across(where(is.character), tolower))


```

```{r}
homeworld_mean = starwars %>% 
  group_by(homeworld) %>%
  summarize(across(where(is.numeric), mean, na.rm = TRUE))
  

```
### Basic / common trouble shooting stuff
```{r}

starwars %>% 
  filter(homeworld = "Naboo")

# Error: Problem with `filter()` input `..1`. x Input `..1` is named. i This usually means that you've used `=` instead of `==`. i Did you mean `homeworld == "Naboo"`? ***Should be == instead of =*** 

```
```{r}

starwars %>% 
  separate(skin_color, into = c("col_1", "col_2"), sep = ",")

```
```{r}
ggplot(mtcars, aes(x = wt, y = mpg)) + 
  geom_point()
```
```{r}

trouble = penguins %>% 
  mutate(across(where(is.numeric), as.character)) %>% 
  mutate(island = fct_relevel(island, c("Dream", "Biscoe", "Torgersen"))) %>% 
  unite(island_yr, c(island, year), sep = "_") %>% 
  filter(species %in% c("Adelie", "Chinstrap")) %>% 
  relocate(year, .after = species) %>% 
  rename(penguin_spp = species)



```

```{r}

library(tidyverse)

df = tribble(
  ~name, ~height, ~hair_color, 
  "Teddy", 2.2, "brown",
  "Khora", 3.1, "white", 
  "Waffle", 1.0, "tan"
)

df %>% filter(name=="Waffle")

```


